Create pass by reference vs pass by value.md
cyrus01337/tags pull request #1
Opened 2024-05-11 13:22 UTC by Parihsz

2024-05-11 17:12 UTC, cyrus01337 commented on pass by reference vs pass by value.md
> +In Luau, variables can be passed by value or by reference depending on their data type.
Remove "In Luau"

2024-05-11 17:18 UTC, cyrus01337 commented on pass by reference vs pass by value.md
> +  - Tables, on the other hand are passed by reference. When you assign a table to another variable or pass it to a function, you're passing a referene to the original table in memory. So, changes mad
Resolve typos.

2024-05-11 17:19 UTC, cyrus01337 commented on pass by reference vs pass by value.md
> +Indirect Change is when you are changing the variable and not the actual value, for example:
"Below is an example of a variable being overwritten, instead of the value being changed:

2024-05-11 17:19 UTC, cyrus01337 commented on pass by reference vs pass by value.md
> +The proper way to do it is:
"Here is the correct way to do it:"

2024-05-11 17:19 UTC, cyrus01337 commented on pass by reference vs pass by value.md
> +In this case, you are overwriting the variable, not changing the value.
This can be removed, the change after simplifies this enough.

2024-05-11 17:20 UTC, cyrus01337 requested changes
Once these have been resolved it'll be good to include.

2024-05-11 17:49 UTC, Parihsz reviewed
fixed

2024-05-12 06:40 UTC, cyrus01337 requested changes

2024-05-12 06:40 UTC, cyrus01337 commented on pass by reference vs pass by value.md
> -Tag Command: pass-by-vs-reference
Change to "pass-value-vs-reference" or "value-vs-reference"

2024-05-15 17:06 UTC, cyrus01337 approved these changes

2024-05-15 17:07 UTC, merged